apriltag:
  ros__parameters:

    image_transport: raw

    family: 36h11
    size: 0.085   # <-- CHANGE THIS to your actual tag size in meters

    max_hamming: 0

    detector:
      threads: 2
      decimate: 2.0
      blur: 0.0
      refine: true

    tag:
      ids:    [0]
      frames: ["tag_0"]
      sizes:  [0.085]   # must match size above
